//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengerShipingCo.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PassengerShippingEntities : DbContext
    {
        public PassengerShippingEntities()
            : base("name=PassengerShippingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Captain> Captain { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Cruise> Cruise { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<PassengerCruise> PassengerCruise { get; set; }
        public virtual DbSet<Port> Port { get; set; }
        public virtual DbSet<Ship> Ship { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
    }
}
