//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengerShipingCo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerCruise
    {
        public int ID { get; set; }
        public int TourID { get; set; }
        public int PassengerID { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
